---
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: production
    image: dirtviz-backend
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - '8000:8000'
    depends_on:
      - postgresql
    volumes:
      - './backend:/app'

  worker:
    build:
      context: ./backend
      target: prodworker
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - backend
      - valkey
    volumes:
      - './backend:/app'

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: production
    image: dirtviz-frontend
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - '3000:80'
    depends_on:
      - backend
    tty: true
    volumes:
      - './frontend/src:/app/src'

  migration:
    build:
      context: ./backend
      target: migration
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - postgresql

  backend-test:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: test
    image: dirtviz-backend-test
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - postgresql
    volumes:
      - './backend:/app'
    profiles:
      - ci
      - test

  backend-lint:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: lint
    image: dirtviz-backend-lint
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - './backend:/app'
    profiles:
      - ci
      - lint

  frontend-test:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: test
    image: dirtviz-frontend-test
    volumes:
      - './frontend:/app'
    profiles:
      - ci
      - test

  frontend-lint:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: lint
    image: dirtviz-frontend-lint
    volumes:
      - './frontend:/app'
      - /app/node_modules
    profiles:
      - ci
      - lint

  valkey:
    image: valkey/valkey:latest
    ports:
      - '6379:6379'

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: dirtviz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dirtviz
    ports:
      - '5432:5432'
    volumes:
      - postgresql-16-data:/var/lib/postgresql/data
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 3g

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=valkey
      - REDIS_1_PORT=6379
    links:
      - valkey
    ports:
      - '6000:80'

volumes:
  postgresql-16-data:
  pgadmin-data:
