export const CHART_CONFIGS = {
  power_voltage: {
    sensor_name: 'POWER_VOLTAGE',
    measurements: ['Voltage'],
    units: ['mV'],
    axisIds: ['y'],
    chartId: 'powerVoltage',
  },
  power_current: {
    sensor_name: 'POWER_CURRENT',
    measurements: ['Current'],
    units: ['uA'],
    axisIds: ['y'],
    chartId: 'powerCurrent',
  },
  teros12_vwc: {
    sensor_name: 'TEROS12_VWC',
    measurements: ['Volumetric Water Content (Raw)'],
    units: ['raw'],
    axisIds: ['y'],
    chartId: 'teros12VWC',
  },
  teros12_vwc_adj: {
    sensor_name: 'TEROS12_VWC_ADJ',
    measurements: ['Volumetric Water Content'],
    units: ['%'],
    axisIds: ['y'],
    axisPolicy: 'vwcPercent',
    chartId: 'teros12VWCADJ',
  },
  teros12_temp: {
    sensor_name: 'TEROS12_TEMP',
    measurements: ['Temperature'],
    units: ['°C'],
    axisIds: ['y'],
    chartId: 'teros12Temp',
  },
  teros12_ec: {
    sensor_name: 'TEROS12_EC',
    measurements: ['Electrical Conductivity'],
    units: ['µS/cm'],
    axisIds: ['y'],
    chartId: 'teros12EC',
  },
  temperature: {
    sensor_name: 'bme280',
    measurements: ['temperature'],
    units: ['°C'],
    axisIds: ['y'],
    chartId: 'bme280',
  },
  bme280Temperature: {
    sensor_name: 'BME280_TEMP',
    measurements: ['Temperature'],
    units: ['°C'],
    axisIds: ['y'],
    chartId: 'bme280temp',
  },
  co2: {
    sensor_name: 'co2',
    measurements: ['co2'],
    units: ['ppm'],
    axisIds: ['y'],
    chartId: 'co2',
  },
  presHum: {
    sensor_name: 'bme280',
    measurements: ['pressure', 'humidity'],
    units: ['kPa', '%'],
    axisIds: ['pressureAxis', 'humidityAxis'],
    chartId: 'presHum',
  },
  bme280Pressure: {
    sensor_name: 'BME280_PRESSURE',
    measurements: ['Pressure'],
    units: ['kPa'],
    axisIds: ['pressureAxis'],
    chartId: 'bme280pressure',
  },
  bme280Humidity: {
    sensor_name: 'BME280_HUMIDITY',
    measurements: ['Humidity'],
    units: ['%'],
    axisIds: ['humidityAxis'],
    chartId: 'bme280humidity',
  },
  sensor: {
    sensor_name: 'phytos31',
    measurements: ['dielectric_permittivity'],
    units: ['1 (unitless)'],
    axisIds: ['y'],
    chartId: 'sensor',
  },
  soilPot: {
    sensor_name: 'teros21',
    measurements: ['soil_water_potential'],
    units: ['kPa'],
    axisIds: ['y'],
    chartId: 'soilPot',
  },
  soilHum: {
    sensor_name: 'sen0308',
    measurements: ['humidity'],
    units: ['%'],
    axisIds: ['y'],
    chartId: 'soilHum',
  },
  waterPress: {
    sensor_name: 'sen0257',
    measurements: ['pressure'],
    units: ['kPa'],
    axisIds: ['y'],
    chartId: 'waterPress',
  },
  waterFlow: {
    sensor_name: 'yfs210c',
    measurements: ['flow'],
    units: ['L/Min'],
    axisIds: ['y'],
    chartId: 'waterFlow',
  },
};
