"""Added server datetime column for data tables

Revision ID: 88337765ad01
Revises: 535eee3c4ba5
Create Date: 2022-08-09 15:00:25.315273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88337765ad01'
down_revision = '535eee3c4ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_data', sa.Column('ts_server', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('teros_data', sa.Column('ts_server', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('teros_data', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teros_data', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('teros_data', 'ts_server')
    op.drop_column('power_data', 'ts_server')
    # ### end Alembic commands ###
