"""Added location and history columns

Revision ID: 066f16929875
Revises: 88337765ad01
Create Date: 2022-11-15 20:13:59.430163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066f16929875'
down_revision = '88337765ad01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell', sa.Column('history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell', 'history')
    # ### end Alembic commands ###
