---
name: Lint and test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

env:
  ENV_FILE: ci.env

permissions:
  contents: read

jobs:
  backend-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up backend-format --abort-on-container-exit

  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up backend-lint --abort-on-container-exit

  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up frontend-lint --abort-on-container-exit

  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up backend-test --abort-on-container-exit

      - name: Copy coverage report
        run: docker compose cp backend-test:/app/.coverage ./.coverage

      - name: Upload backend coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./.coverage
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up frontend-test --abort-on-container-exit

      - name: Copy coverage report
        run: docker compose cp frontend-test:/app/coverage/coverage-final.json ./coverage-final.json

      - name: Upload frontend coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage-final.json
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}

  stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Start services
        run:
          docker compose up -d

      - name: Wait for services to start
        run: sleep 10s

      - name: Save timestamp
        id: timestamp
        run: echo "start_time=$(date -Is)" >> $GITHUB_OUTPUT

      - name: Save all logs
        if: always()
        run: docker compose logs -t > dirtviz.log

      - name: Save short logs
        if: always()
        run: |
          SINCE="${{ steps.timestamp.outputs.start_time }}"
          if [ -n "$SINCE" ]; then
            docker compose logs -t --since "$SINCE" > dirtviz_short.log
          else
            docker compose logs -t > dirtviz_short.log
          fi

      - name: Check for errors
        run: "! grep -i 'error' dirtviz_short.log"

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: DirtViz Logs
          path: |
            dirtviz.log
            dirtviz_short.log
