---
name: Lint and test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [backend-lint, backend-test, frontend-lint, frontend-test]
    env:
      ENV_FILE: ci.env

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build containers
        run: docker compose --profile ci build

      - name: Lint backend
        run: docker compose up ${{ matrix.container }} --abort-on-container-exit

  stack:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: ci.env

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Start services
        run:
          docker compose up -d

      - name: Wait for services to start
        run: sleep 10s

      - name: Save timestamp
        id: timestamp
        run: echo "start_time=$(date -Is)" >> $GITHUB_OUTPUT

      - name: Save all logs
        if: always()
        run: docker compose logs -t > dirtviz.log

      - name: Save short logs
        if: always()
        run: |
          SINCE="${{ steps.timestamp.outputs.start_time }}"
          if [ -n "$SINCE" ]; then
            docker compose logs -t --since "$SINCE" > dirtviz_short.log
          else
            docker compose logs -t > dirtviz_short.log
          fi

      - name: Check for errors
        run: "! grep -i 'error' dirtviz_short.log"

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: DirtViz Logs
          path: |
            dirtviz.log
            dirtviz_short.log
