"""removed-unique-dev-eui

Revision ID: 14612231efb8
Revises: 74d2b23d3a42
Create Date: 2026-07-03 19:31:14.075284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14612231efb8'
down_revision = '74d2b23d3a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_logger_device_eui_norm'), postgresql_where="((device_eui IS NOT NULL) AND (TRIM(BOTH FROM device_eui) <> ''::text))")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_logger_device_eui_norm'), [sa.literal_column('upper(TRIM(BOTH FROM device_eui))')], unique=True, postgresql_where="((device_eui IS NOT NULL) AND (TRIM(BOTH FROM device_eui) <> ''::text))")

    # ### end Alembic commands ###
