"""added indexes for timestamps

Revision ID: 15816217ea64
Revises: 2c563dcd2920
Create Date: 2024-05-20 12:02:37.695736

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15816217ea64"
down_revision = "2c563dcd2920"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_data_ts"), ["ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_data_ts_server"), ["ts_server"], unique=False
        )

    with op.batch_alter_table("power_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_power_data_ts"), ["ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_power_data_ts_server"), ["ts_server"], unique=False
        )

    with op.batch_alter_table("teros_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teros_data_ts"), ["ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_teros_data_ts_server"), ["ts_server"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teros_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teros_data_ts_server"))
        batch_op.drop_index(batch_op.f("ix_teros_data_ts"))

    with op.batch_alter_table("power_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_power_data_ts_server"))
        batch_op.drop_index(batch_op.f("ix_power_data_ts"))

    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_ts_server"))
        batch_op.drop_index(batch_op.f("ix_data_ts"))

    # ### end Alembic commands ###
