"""added is_public boolean to cell

Revision ID: 2a9d1af60f24
Revises: 14612231efb8
Create Date: 2026-10-02 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a9d1af60f24"
down_revision = "14612231efb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cell", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_public", sa.Boolean(), nullable=False, server_default="true")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cell", schema=None) as batch_op:
        batch_op.drop_column("is_public")

    # ### end Alembic commands ###
