"""Fixed data.sensor_id fk to sensor.id

Revision ID: 2c563dcd2920
Revises: f44a21ea53a4
Create Date: 2024-04-20 00:32:40.589573

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c563dcd2920"
down_revision = "f44a21ea53a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.drop_constraint("data_sensor_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "sensor", ["sensor_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "data_sensor_id_fkey", "cell", ["sensor_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###
