"""added_user_cell_table

Revision ID: 47822a5f0b44
Revises: d09945f167e5
Create Date: 2025-11-17 05:10:15.689640

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "47822a5f0b44"
down_revision = "d09945f167e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cell_user",
        sa.Column("cell_id", sa.Integer(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cell_id"],
            ["cell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("cell_id", "user_id"),
    )
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True)
        )
        batch_op.create_foreign_key(None, "user", ["created_by"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("created_by")
        batch_op.drop_column("created_at")
        batch_op.drop_column("description")

    op.drop_table("cell_user")
    # ### end Alembic commands ###
