"""Added unique constraint for cell, logger

Revision ID: 535eee3c4ba5
Revises: 7f24337773d6
Create Date: 2022-08-09 14:30:23.059143

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "535eee3c4ba5"
down_revision = "7f24337773d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cell", ["name"])
    op.create_unique_constraint(None, "logger", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "logger", type_="unique")
    op.drop_constraint(None, "cell", type_="unique")
    # ### end Alembic commands ###
