"""add api key column to user db table

Revision ID: 74d2b23d3a42
Revises: a6d9c5f2e1b3
Create Date: 2026-05-13 21:02:48.992504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d2b23d3a42'
down_revision = 'a6d9c5f2e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_api_key', ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_key', type_='unique')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
