"""Added cascading delete for cell foreign keys

Revision ID: 7f24337773d6
Revises: 19d307d816a1
Create Date: 2022-08-09 13:54:45.763913

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f24337773d6"
down_revision = "19d307d816a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "power_data", "logger_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("power_data_cell_id_fkey", "power_data", type_="foreignkey")
    op.create_foreign_key(
        None, "power_data", "cell", ["cell_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("teros_data_cell_id_fkey", "teros_data", type_="foreignkey")
    op.create_foreign_key(
        None, "teros_data", "cell", ["cell_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teros_data", type_="foreignkey")
    op.create_foreign_key(
        "teros_data_cell_id_fkey", "teros_data", "cell", ["cell_id"], ["id"]
    )
    op.drop_constraint(None, "power_data", type_="foreignkey")
    op.create_foreign_key(
        "power_data_cell_id_fkey", "power_data", "cell", ["cell_id"], ["id"]
    )
    op.alter_column(
        "power_data", "logger_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
