"""Added generic sensor and data tables

Revision ID: 8e6bc63a081f
Revises: c7c5894af080
Create Date: 2024-01-13 15:03:42.699096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6bc63a081f'
down_revision = 'c7c5894af080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.Text(), nullable=False))
        batch_op.drop_column('meas_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meas_type', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###
