"""added_index_to_power_data_and_teros

Revision ID: c098fa612f87
Revises: 596bac7fbbee
Create Date: 2025-07-29 21:25:53.921482

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c098fa612f87"
down_revision = "596bac7fbbee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.create_index(
            "idx_data_sensor_id_ts", ["sensor_id", "ts"], unique=False
        )
        batch_op.drop_table_comment(
            existing_comment="Power and TEROS data migrated from legacy tables on 2025-06-30"
        )

    with op.batch_alter_table("power_data", schema=None) as batch_op:
        batch_op.create_index(
            "idx_power_data_cell_id_ts", ["cell_id", "ts"], unique=False
        )

    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.create_index("idx_sensor_cell_id", ["cell_id"], unique=False)

    with op.batch_alter_table("teros_data", schema=None) as batch_op:
        batch_op.create_index(
            "idx_teros_data_cell_id_ts", ["cell_id", "ts"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teros_data", schema=None) as batch_op:
        batch_op.drop_index("idx_teros_data_cell_id_ts")

    with op.batch_alter_table("sensor", schema=None) as batch_op:
        batch_op.drop_index("idx_sensor_cell_id")

    with op.batch_alter_table("power_data", schema=None) as batch_op:
        batch_op.drop_index("idx_power_data_cell_id_ts")

    with op.batch_alter_table("data", schema=None) as batch_op:
        batch_op.create_table_comment(
            "Power and TEROS data migrated from legacy tables on 2025-06-30",
            existing_comment=None,
        )
        batch_op.drop_index("idx_data_sensor_id_ts")

    # ### end Alembic commands ###
