"""added water potential and raw volumetric water content

Revision ID: c751acdaab3f
Revises: 88337765ad01
Create Date: 2023-06-02 15:38:36.412041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c751acdaab3f'
down_revision = '88337765ad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teros_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_vwc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_pot', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teros_data', schema=None) as batch_op:
        batch_op.drop_column('water_pot')
        batch_op.drop_column('raw_vwc')

    # ### end Alembic commands ###
