"""added User ID integer field to cell

Revision ID: caf4baaaa14f
Revises: 15816217ea64
Create Date: 2024-05-30 01:45:16.100418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf4baaaa14f'
down_revision = '15816217ea64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # This downgrade is broken, very common in alembic where this 
    # downgrade writes None as the constraint name although  it does 
    # not exist. Self breaks. To fix, comment out the drop_constraint
    # line and run the downgrade. Then manually delete the foreign_key.
    # Hopefully, we can fix this down the line as this downgrade might
    # be neccesary for development of this implementation.
    # https://github.com/miguelgrinberg/Flask-Migrate/issues/155
    # 
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
