"""Added user and token tables

Revision ID: eb87a7373607
Revises: 74f0f195babd
Create Date: 2024-01-22 23:29:48.128444

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb87a7373607"
down_revision = "74f0f195babd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=72), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "oauth_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    with op.batch_alter_table("oauth_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_token_refresh_token"), ["refresh_token"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_token_refresh_token"))

    op.drop_table("oauth_token")
    op.drop_table("user")
    # ### end Alembic commands ###
