"""Added updated_at field for tokens

Revision ID: f44a21ea53a4
Revises: eb87a7373607
Create Date: 2024-02-03 21:50:51.468259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44a21ea53a4'
down_revision = 'eb87a7373607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_key', ['id'])

    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
