"""updated loggers for ttn registration

Revision ID: fd48c93ccf7b
Revises: c098fa612f87
Create Date: 2025-08-27 12:52:29.773199

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fd48c93ccf7b"
down_revision = "c098fa612f87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logger", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("device_eui", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("date_created", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("user_id", sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ["uuid"])
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("mac")
        batch_op.drop_column("hostname")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logger", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hostname", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("mac", postgresql.MACADDR(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("user_id")
        batch_op.drop_column("date_created")
        batch_op.drop_column("description")
        batch_op.drop_column("device_eui")
        batch_op.drop_column("type")
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
